### ISSUE TITLE
fast parseTags doesn't parse "<td class=s" the same

### ISSUE THREAD

**Issue by erantapaa** [vshabanov/fast-tagsoup#3]
Here is a problem I ran into...

I tried to define a instance for `TagRep ByteString` like this:

``` haskell
import Text.HTML.TagSoup hiding (parseTags, renderTags, (~==))
import qualified Text.HTML.TagSoup as TS
import Text.HTML.TagSoup.Fast
import qualified Data.ByteString.Char8 as BS
...
instance TagRep ByteString where
    toTagRep x = case parseTags x of
                     [a] -> toTagRep a
                     _ -> error $ "When using a TagRep it must be exactly one tag, you gave: " ++ BS.unpack x
```

and `parseTags $ (BS.pack "<td class=s")` didn't create the correct tag.

However, things worked if I changed the instance definition to use `TS.parseTags` instead of the `parseTags` from the fast package:

``` haskell
instance TagRep ByteString where
    toTagRep x = case TS.parseTags x of
                     [a] -> toTagRep a
                     _ -> error ...
```

it worked correctly.

**Comment by erantapaa** [comment]
The problem is that `parseTags` doesn't check for the end of input when parsing a tag name, attribute name or attribute value. I guess the advice / work-around is to always include the ending `>` on tag specs.

**Comment by vshabanov** [comment]
Fixed. New version is uploaded to Hackage.
